# Generated by Django 5.0.6 on 2024-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('news', 'News'), ('general', 'General'), ('art', 'Art'), ('lifestyle', 'LifeStyle'), ('health', 'Health'), ('fun', 'Fun')], max_length=50),
        ),
    ]
